added search method , lvl node etc
DanerSound/ProgettoASD1718 pull request #8
Opened 2018-06-06 15:47 UTC by DanerSound

2018-06-06 17:01 UTC, Wabri requested changes

2018-06-06 17:01 UTC, Wabri commented on ProgettoASD1718/src/base/AlberoLF.java
> +		if (Node.equals(root)) {
fai un override del metodo equals nella classe NodoLF

2018-06-06 17:01 UTC, Wabri commented on ProgettoASD1718/src/base/AlberoLF.java
> +		if (Node.equals(root)) {
Non perchè sia sbagliato ma per convenzione e completezza i metodi toString e equals vengono overridati quando usati su un oggetto

2018-06-06 17:01 UTC, Wabri commented on ProgettoASD1718/src/base/AlberoLF.java
> +				searchList.removeFirst();
attento alla formattazione

2018-06-06 17:01 UTC, Wabri commented on ProgettoASD1718/src/base/AlberoLF.java
> +	public String getFatherOf(NodoLF<T> Node) {
sei sicuro che l'output debba essere una stringa?

2018-06-06 17:01 UTC, Wabri commented on ProgettoASD1718/src/base/AlberoLF.java
> +		String father=tmp.getFather().getInf().toString();
invece di istanziare una variabile stringa father puoi mettere l'implementazione di questa direttamente nel return del metodo

2018-06-06 17:01 UTC, Wabri commented on ProgettoASD1718/src/base/AlberoLF.java
> +		NodoLF<T>tmp=searchNode(Node);
e se il nodo non c'è?

2018-06-06 17:01 UTC, Wabri commented on ProgettoASD1718/src/base/AlberoLF.java
> +		NodoLF<T> tmp= searchNode(Node);
e se il nodo non c'è?

2018-06-09 00:01 UTC, DanerSound commented on ProgettoASD1718/src/base/AlberoLF.java
> +				searchList.removeFirst();
fatto.

2018-06-09 00:06 UTC, DanerSound commented on ProgettoASD1718/src/base/AlberoLF.java
> +	public String getFatherOf(NodoLF<T> Node) {
si, io chiamo la funzione toString del nodo per farmi restiturire il valore contenuto nel nodo qualche esso sia.

2018-06-09 00:07 UTC, DanerSound commented on ProgettoASD1718/src/base/AlberoLF.java
> +		String father=tmp.getFather().getInf().toString();
fatto.

2018-06-09 00:09 UTC, DanerSound commented on ProgettoASD1718/src/base/AlberoLF.java
> +		NodoLF<T>tmp=searchNode(Node);
vuole dire che la mamma si è divertita parecchio

2018-06-09 00:16 UTC, DanerSound commented on ProgettoASD1718/src/base/AlberoLF.java
> +	public String getFatherOf(NodoLF<T> Node) {
cosi come l'ho pensato io,  voglio che sia una stringa

2018-06-09 00:23 UTC, DanerSound commented on ProgettoASD1718/src/base/AlberoLF.java
> +		if (Node.equals(root)) {
ho un dubbio attroce, sto raggionando a tratti magari perche sono le 2.30 del mattino

2018-06-11 12:48 UTC, merged